output_dir: results_patrol_final


hydra:
  run:
    dir: results/${output_dir}



problem:

  use_theta : True
  seed_val: 0
  time_out_time: 200
  #Robot
  radius: 0.5
  vehicle_dynamics: True
  vehicle_model: 0.001

  #Noise model
  use_noise: True
  sensor_noise: 0.03
  action_noise: 0.03

  # Core GPMP config
  use_GP_inter: True
  delta_t : 0.25
  inter_step: 4
  avg_vel: 0.3

  #GPMP-Factor related
  cost_sigma: 0.1
  epsilon_dist: 1.0
  #sigma_goal: 2.0
  sigma_start: 0.0001
  use_trustregion_opt: True

  # Common
  use_vel_limit: True
  sigma_vel_limit: 0.01
  node_budget: 100
  sdf_side: 60.0

  #Receding Horizon specific things
  
  init_fraction_length: 0.2
  goal_region_threshold: 1.0
  connection_threshold: 0.5
  same_state_init: True
  sigma_goal_rh: 5.0
  #RRT specific things
  
  width: 20.0
  height: 20.0
  move_along_val: 0.5
  move_along_val_theta: 0.2
  use_prev_graph: True
  sigma_goal_costco: 5.0

  costco_goal_scaling: 0.0
